name: Blood Pressure Monolith yml
on:
  workflow_dispatch:
  schedule:
    - cron: '05/15 14-16 * * *'
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2
      - name: Install dependencies 📦
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false
  
  tests2:        
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2
      # we re-install the dependencies
      # in practice, this should pull the cached
      # dependencies from the previous install job
      - name: Install dependencies 📦
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false
          record: true

      - name: App Percy
        run: npm install --save-dev @percy/cli
        
        
      - name: Run tests with "@bpTest" 🧪
        run: |
         npx percy exec -- cypress run --headless --record --key b877676e-70aa-40b3-84da-261dcc19e396 --env tags="@bpcTest" --config screenshotOnRunFailure=true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          
